### ISSUE TITLE
Incorrect installation instructions? 

### ISSUE THREAD

**Issue by NfNitLoop** [seishun/deno-protobuf#2]
Hello!  I'm playing around with Deno and writing a thing that uses protobuf.  I've been using the upstream `protoc-gen-ts`, so when I came across this version modified for Deno I thought it'd work great.  But, I'm running into some issues.

I've already cloned the repo, and run `npm install -g` in the `gen` directory.

Now, when I run `protoc`, I get this error:

```
PS C:\Users\Cody\code\deno-feed\feoblog-client\private\protobuf> protoc --proto_path=.  --ts_out=dist .\feoblog.proto
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module 'google-protobuf/google/protobuf/compiler/plugin_pb'
Require stack:
- C:\Users\Cody\code\deno-feed\feoblog-client\private\protobuf\deno-protobuf\gen\index.js
- C:\Users\Cody\code\deno-feed\feoblog-client\private\protobuf\deno-protobuf\gen\bin\protoc-gen-ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Cody\code\deno-feed\feoblog-client\private\protobuf\deno-protobuf\gen\index.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Cody\\code\\deno-feed\\feoblog-client\\private\\protobuf\\deno-protobuf\\gen\\index.js',
    'C:\\Users\\Cody\\code\\deno-feed\\feoblog-client\\private\\protobuf\\deno-protobuf\\gen\\bin\\protoc-gen-ts'
  ]
}
--ts_out: protoc-gen-ts: Plugin failed with status code 1.
```

Aaah.  I think I found the issue?  It looks like I need to both `npm install` *and* `npm install -g`.  Is that a quirk of NPM? Might be worth updating the README?

**Comment by NfNitLoop** [comment]
Unrelated question, but while we're on the topic of me being unfamiliar with `npm`:  What's the [runtime] subdirectory? I don't see it referenced by `index.js`

[runtime]: https://github.com/seishun/deno-protobuf/tree/master/runtime

**Comment by seishun** [comment]
`npm install -g` works just fine for me. Try on another machine.

>What's the runtime subdirectory? I don't see it referenced by index.js

It contains files used by the generated code.
